# Build plan from the provider
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

# nixpacks.toml
[phases.setup]
nixPkgs = ['alpinejs', 'cowsay']

# Merged plan
[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'cowsay']

#[phases.setup]
#  # uses bun 1.0.18
#  nixpkgsArchive = '9c69bc8cae2f3b38536a50801961e2e62da13595'
#
#[start]
#  cmd = "bun run migrate && bun run start"
