# Build plan from the provider
[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'alpinejs', 'cowsay']
[phases.build]
cmds = ['yarn run build']

#
#[start]
#cmd = "yarn start"


## BUN STUFF
### https://cdbrw.medium.com/deploy-your-first-bun-app-railway-fly-io-d65725b2e90d
#[phases.setup]
#  # uses bun 1.0.18
#  nixpkgsArchive = '9c69bc8cae2f3b38536a50801961e2e62da13595'
#
#[start]
#  cmd = "bun run migrate && bun run start"
